//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.SvcRef_BTCL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenRequest", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    public partial class TokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenNumber {
            get {
                return this.TokenNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenNumberField, value) != true)) {
                    this.TokenNumberField = value;
                    this.RaisePropertyChanged("TokenNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillRequest", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    public partial class BillRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BKBTitas.SvcRef_BTCL.BillLedger[] BillDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TXNNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BKBTitas.SvcRef_BTCL.BillLedger[] BillDetails {
            get {
                return this.BillDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDetailsField, value) != true)) {
                    this.BillDetailsField = value;
                    this.RaisePropertyChanged("BillDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeCode {
            get {
                return this.ExchangeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeCodeField, value) != true)) {
                    this.ExchangeCodeField = value;
                    this.RaisePropertyChanged("ExchangeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TXNNumber {
            get {
                return this.TXNNumberField;
            }
            set {
                if ((this.TXNNumberField.Equals(value) != true)) {
                    this.TXNNumberField = value;
                    this.RaisePropertyChanged("TXNNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillLedger", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BKBTitas.SvcRef_BTCL.BillLedgerHistory))]
    public partial class BillLedger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BTCL_AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillPayStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TXNNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VATField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BTCL_Amount {
            get {
                return this.BTCL_AmountField;
            }
            set {
                if ((this.BTCL_AmountField.Equals(value) != true)) {
                    this.BTCL_AmountField = value;
                    this.RaisePropertyChanged("BTCL_Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillMonth {
            get {
                return this.BillMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.BillMonthField, value) != true)) {
                    this.BillMonthField = value;
                    this.RaisePropertyChanged("BillMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNo {
            get {
                return this.BillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNoField, value) != true)) {
                    this.BillNoField = value;
                    this.RaisePropertyChanged("BillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillPayStatus {
            get {
                return this.BillPayStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BillPayStatusField, value) != true)) {
                    this.BillPayStatusField = value;
                    this.RaisePropertyChanged("BillPayStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillStatus {
            get {
                return this.BillStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BillStatusField, value) != true)) {
                    this.BillStatusField = value;
                    this.RaisePropertyChanged("BillStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillYear {
            get {
                return this.BillYearField;
            }
            set {
                if ((object.ReferenceEquals(this.BillYearField, value) != true)) {
                    this.BillYearField = value;
                    this.RaisePropertyChanged("BillYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeCode {
            get {
                return this.ExchangeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeCodeField, value) != true)) {
                    this.ExchangeCodeField = value;
                    this.RaisePropertyChanged("ExchangeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastPayDate {
            get {
                return this.LastPayDateField;
            }
            set {
                if ((this.LastPayDateField.Equals(value) != true)) {
                    this.LastPayDateField = value;
                    this.RaisePropertyChanged("LastPayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TXNNumber {
            get {
                return this.TXNNumberField;
            }
            set {
                if ((this.TXNNumberField.Equals(value) != true)) {
                    this.TXNNumberField = value;
                    this.RaisePropertyChanged("TXNNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VAT {
            get {
                return this.VATField;
            }
            set {
                if ((this.VATField.Equals(value) != true)) {
                    this.VATField = value;
                    this.RaisePropertyChanged("VAT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillLedgerHistory", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    public partial class BillLedgerHistory : BKBTitas.SvcRef_BTCL.BillLedger {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BANK_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BRANCH_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BANK_ID {
            get {
                return this.BANK_IDField;
            }
            set {
                if ((this.BANK_IDField.Equals(value) != true)) {
                    this.BANK_IDField = value;
                    this.RaisePropertyChanged("BANK_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BRANCH_ID {
            get {
                return this.BRANCH_IDField;
            }
            set {
                if ((this.BRANCH_IDField.Equals(value) != true)) {
                    this.BRANCH_IDField = value;
                    this.RaisePropertyChanged("BRANCH_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BKBTitas.SvcRef_BTCL.PaymentCancelResponse))]
    public partial class BillPaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TXNNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TXNNumber {
            get {
                return this.TXNNumberField;
            }
            set {
                if ((this.TXNNumberField.Equals(value) != true)) {
                    this.TXNNumberField = value;
                    this.RaisePropertyChanged("TXNNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentCancelResponse", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    public partial class PaymentCancelResponse : BKBTitas.SvcRef_BTCL.BillPaymentResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillPaidHistory", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    public partial class BillPaidHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BKBTitas.SvcRef_BTCL.BillLedgerHistory[] BillDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TXNNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BKBTitas.SvcRef_BTCL.BillLedgerHistory[] BillDetails {
            get {
                return this.BillDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDetailsField, value) != true)) {
                    this.BillDetailsField = value;
                    this.RaisePropertyChanged("BillDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeCode {
            get {
                return this.ExchangeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeCodeField, value) != true)) {
                    this.ExchangeCodeField = value;
                    this.RaisePropertyChanged("ExchangeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TXNNumber {
            get {
                return this.TXNNumberField;
            }
            set {
                if ((this.TXNNumberField.Equals(value) != true)) {
                    this.TXNNumberField = value;
                    this.RaisePropertyChanged("TXNNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResponse", Namespace="http://schemas.datacontract.org/2004/07/SLMS.BillCollection.BankAPI.Model")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRef_BTCL.ISLMS_Service")]
    public interface ISLMS_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/TestService", ReplyAction="http://tempuri.org/ISLMS_Service/TestServiceResponse")]
        BKBTitas.SvcRef_BTCL.TokenRequest TestService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/TestService", ReplyAction="http://tempuri.org/ISLMS_Service/TestServiceResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.TokenRequest> TestServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/Test", ReplyAction="http://tempuri.org/ISLMS_Service/TestResponse")]
        BKBTitas.SvcRef_BTCL.TokenRequest Test(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/Test", ReplyAction="http://tempuri.org/ISLMS_Service/TestResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.TokenRequest> TestAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/GetTokenByUser", ReplyAction="http://tempuri.org/ISLMS_Service/GetTokenByUserResponse")]
        BKBTitas.SvcRef_BTCL.TokenRequest GetTokenByUser(string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/GetTokenByUser", ReplyAction="http://tempuri.org/ISLMS_Service/GetTokenByUserResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.TokenRequest> GetTokenByUserAsync(string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/GetBillLedger", ReplyAction="http://tempuri.org/ISLMS_Service/GetBillLedgerResponse")]
        BKBTitas.SvcRef_BTCL.BillRequest GetBillLedger(int TXNNumber, string UserID, string TokenNumber, string ExchangeCode, string PhoneNumber, string LastPayDate, string PayStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/GetBillLedger", ReplyAction="http://tempuri.org/ISLMS_Service/GetBillLedgerResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.BillRequest> GetBillLedgerAsync(int TXNNumber, string UserID, string TokenNumber, string ExchangeCode, string PhoneNumber, string LastPayDate, string PayStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/BillPaymentRequest", ReplyAction="http://tempuri.org/ISLMS_Service/BillPaymentRequestResponse")]
        BKBTitas.SvcRef_BTCL.BillPaymentResponse BillPaymentRequest(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, decimal PaidAmount, string BillStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/BillPaymentRequest", ReplyAction="http://tempuri.org/ISLMS_Service/BillPaymentRequestResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.BillPaymentResponse> BillPaymentRequestAsync(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, decimal PaidAmount, string BillStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/GetPaymentCollectionHistory", ReplyAction="http://tempuri.org/ISLMS_Service/GetPaymentCollectionHistoryResponse")]
        BKBTitas.SvcRef_BTCL.BillPaidHistory GetPaymentCollectionHistory(int TXNNumber, string UserID, string TokenNumber, string FromDate, string ToDate, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/GetPaymentCollectionHistory", ReplyAction="http://tempuri.org/ISLMS_Service/GetPaymentCollectionHistoryResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.BillPaidHistory> GetPaymentCollectionHistoryAsync(int TXNNumber, string UserID, string TokenNumber, string FromDate, string ToDate, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/ChangePasswordRequest", ReplyAction="http://tempuri.org/ISLMS_Service/ChangePasswordRequestResponse")]
        BKBTitas.SvcRef_BTCL.ChangePasswordResponse ChangePasswordRequest(string UserID, string TokenNumber, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/ChangePasswordRequest", ReplyAction="http://tempuri.org/ISLMS_Service/ChangePasswordRequestResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.ChangePasswordResponse> ChangePasswordRequestAsync(string UserID, string TokenNumber, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/PaymentCancelRequest", ReplyAction="http://tempuri.org/ISLMS_Service/PaymentCancelRequestResponse")]
        BKBTitas.SvcRef_BTCL.PaymentCancelResponse PaymentCancelRequest(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, string BillStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMS_Service/PaymentCancelRequest", ReplyAction="http://tempuri.org/ISLMS_Service/PaymentCancelRequestResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.PaymentCancelResponse> PaymentCancelRequestAsync(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, string BillStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLMS_ServiceChannel : BKBTitas.SvcRef_BTCL.ISLMS_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLMS_ServiceClient : System.ServiceModel.ClientBase<BKBTitas.SvcRef_BTCL.ISLMS_Service>, BKBTitas.SvcRef_BTCL.ISLMS_Service {
        
        public SLMS_ServiceClient() {
        }
        
        public SLMS_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLMS_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLMS_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLMS_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BKBTitas.SvcRef_BTCL.TokenRequest TestService() {
            return base.Channel.TestService();
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.TokenRequest> TestServiceAsync() {
            return base.Channel.TestServiceAsync();
        }
        
        public BKBTitas.SvcRef_BTCL.TokenRequest Test(string value) {
            return base.Channel.Test(value);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.TokenRequest> TestAsync(string value) {
            return base.Channel.TestAsync(value);
        }
        
        public BKBTitas.SvcRef_BTCL.TokenRequest GetTokenByUser(string UserID, string Password) {
            return base.Channel.GetTokenByUser(UserID, Password);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.TokenRequest> GetTokenByUserAsync(string UserID, string Password) {
            return base.Channel.GetTokenByUserAsync(UserID, Password);
        }
        
        public BKBTitas.SvcRef_BTCL.BillRequest GetBillLedger(int TXNNumber, string UserID, string TokenNumber, string ExchangeCode, string PhoneNumber, string LastPayDate, string PayStatus) {
            return base.Channel.GetBillLedger(TXNNumber, UserID, TokenNumber, ExchangeCode, PhoneNumber, LastPayDate, PayStatus);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.BillRequest> GetBillLedgerAsync(int TXNNumber, string UserID, string TokenNumber, string ExchangeCode, string PhoneNumber, string LastPayDate, string PayStatus) {
            return base.Channel.GetBillLedgerAsync(TXNNumber, UserID, TokenNumber, ExchangeCode, PhoneNumber, LastPayDate, PayStatus);
        }
        
        public BKBTitas.SvcRef_BTCL.BillPaymentResponse BillPaymentRequest(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, decimal PaidAmount, string BillStatus) {
            return base.Channel.BillPaymentRequest(TXNNumber, UserID, TokenNumber, BranchCode, ExchangeCode, PhoneNumber, LastPayDate, PaidAmount, BillStatus);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.BillPaymentResponse> BillPaymentRequestAsync(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, decimal PaidAmount, string BillStatus) {
            return base.Channel.BillPaymentRequestAsync(TXNNumber, UserID, TokenNumber, BranchCode, ExchangeCode, PhoneNumber, LastPayDate, PaidAmount, BillStatus);
        }
        
        public BKBTitas.SvcRef_BTCL.BillPaidHistory GetPaymentCollectionHistory(int TXNNumber, string UserID, string TokenNumber, string FromDate, string ToDate, string BranchCode) {
            return base.Channel.GetPaymentCollectionHistory(TXNNumber, UserID, TokenNumber, FromDate, ToDate, BranchCode);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.BillPaidHistory> GetPaymentCollectionHistoryAsync(int TXNNumber, string UserID, string TokenNumber, string FromDate, string ToDate, string BranchCode) {
            return base.Channel.GetPaymentCollectionHistoryAsync(TXNNumber, UserID, TokenNumber, FromDate, ToDate, BranchCode);
        }
        
        public BKBTitas.SvcRef_BTCL.ChangePasswordResponse ChangePasswordRequest(string UserID, string TokenNumber, string OldPassword, string NewPassword) {
            return base.Channel.ChangePasswordRequest(UserID, TokenNumber, OldPassword, NewPassword);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.ChangePasswordResponse> ChangePasswordRequestAsync(string UserID, string TokenNumber, string OldPassword, string NewPassword) {
            return base.Channel.ChangePasswordRequestAsync(UserID, TokenNumber, OldPassword, NewPassword);
        }
        
        public BKBTitas.SvcRef_BTCL.PaymentCancelResponse PaymentCancelRequest(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, string BillStatus) {
            return base.Channel.PaymentCancelRequest(TXNNumber, UserID, TokenNumber, BranchCode, ExchangeCode, PhoneNumber, LastPayDate, BillStatus);
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCL.PaymentCancelResponse> PaymentCancelRequestAsync(int TXNNumber, string UserID, string TokenNumber, string BranchCode, string ExchangeCode, string PhoneNumber, string LastPayDate, string BillStatus) {
            return base.Channel.PaymentCancelRequestAsync(TXNNumber, UserID, TokenNumber, BranchCode, ExchangeCode, PhoneNumber, LastPayDate, BillStatus);
        }
    }
}
