//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.SvcRef_BTCLBoss {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.ztesoft.zsmart/service", ConfigurationName="SvcRef_BTCLBoss.CrmWebServicesPortType")]
    public interface CrmWebServicesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:QueryServiceStatus", ReplyAction="urn:QueryServiceStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusResponse QueryServiceStatus(BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:QueryServiceStatus", ReplyAction="urn:QueryServiceStatusResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusResponse> QueryServiceStatusAsync(BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Bill", ReplyAction="urn:BillResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.BillResponse Bill(BKBTitas.SvcRef_BTCLBoss.BillRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Bill", ReplyAction="urn:BillResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.BillResponse> BillAsync(BKBTitas.SvcRef_BTCLBoss.BillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BillByCust", ReplyAction="urn:BillByCustResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.BillByCustResponse BillByCust(BKBTitas.SvcRef_BTCLBoss.BillByCustRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:BillByCust", ReplyAction="urn:BillByCustResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.BillByCustResponse> BillByCustAsync(BKBTitas.SvcRef_BTCLBoss.BillByCustRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Token", ReplyAction="urn:TokenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.TokenResponse Token(BKBTitas.SvcRef_BTCLBoss.TokenRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Token", ReplyAction="urn:TokenResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.TokenResponse> TokenAsync(BKBTitas.SvcRef_BTCLBoss.TokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BillPayment", ReplyAction="urn:BillPaymentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.BillPaymentResponse BillPayment(BKBTitas.SvcRef_BTCLBoss.BillPaymentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:BillPayment", ReplyAction="urn:BillPaymentResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.BillPaymentResponse> BillPaymentAsync(BKBTitas.SvcRef_BTCLBoss.BillPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SetService", ReplyAction="urn:SetServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.SetServiceResponse SetService(BKBTitas.SvcRef_BTCLBoss.SetServiceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:SetService", ReplyAction="urn:SetServiceResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.SetServiceResponse> SetServiceAsync(BKBTitas.SvcRef_BTCLBoss.SetServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChangePassword", ReplyAction="urn:ChangePasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.ChangePasswordResponse ChangePassword(BKBTitas.SvcRef_BTCLBoss.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChangePassword", ReplyAction="urn:ChangePasswordResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.ChangePasswordResponse> ChangePasswordAsync(BKBTitas.SvcRef_BTCLBoss.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:PaymentHistory", ReplyAction="urn:PaymentHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.PaymentHistoryResponse PaymentHistory(BKBTitas.SvcRef_BTCLBoss.PaymentHistoryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:PaymentHistory", ReplyAction="urn:PaymentHistoryResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.PaymentHistoryResponse> PaymentHistoryAsync(BKBTitas.SvcRef_BTCLBoss.PaymentHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:QueryUserProfile4Basic", ReplyAction="urn:QueryUserProfile4BasicResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicResponse QueryUserProfile4Basic(BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:QueryUserProfile4Basic", ReplyAction="urn:QueryUserProfile4BasicResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicResponse> QueryUserProfile4BasicAsync(BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:PaymentCancel", ReplyAction="urn:PaymentCancelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BKBTitas.SvcRef_BTCLBoss.PaymentCancelResponse PaymentCancel(BKBTitas.SvcRef_BTCLBoss.PaymentCancelRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:PaymentCancel", ReplyAction="urn:PaymentCancelResponse")]
        System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.PaymentCancelResponse> PaymentCancelAsync(BKBTitas.SvcRef_BTCLBoss.PaymentCancelRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string channelCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ChannelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
                this.RaisePropertyChanged("ChannelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tPaymentCancelRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tXNNumberField;
        
        private string userIDField;
        
        private string tokenNumberField;
        
        private string branchCodeField;
        
        private string bankCodeField;
        
        private string billNoField;
        
        private string billStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TXNNumber {
            get {
                return this.tXNNumberField;
            }
            set {
                this.tXNNumberField = value;
                this.RaisePropertyChanged("TXNNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
                this.RaisePropertyChanged("TokenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BillNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
                this.RaisePropertyChanged("BillNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string BillStatus {
            get {
                return this.billStatusField;
            }
            set {
                this.billStatusField = value;
                this.RaisePropertyChanged("BillStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tQueryUserProfile4BasicRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mSISDNField;
        
        private string userPwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string MSISDN {
            get {
                return this.mSISDNField;
            }
            set {
                this.mSISDNField = value;
                this.RaisePropertyChanged("MSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string UserPwd {
            get {
                return this.userPwdField;
            }
            set {
                this.userPwdField = value;
                this.RaisePropertyChanged("UserPwd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tPaymentHistoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tXNNumberField;
        
        private string userIDField;
        
        private string tokenNumberField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private string branchCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TXNNumber {
            get {
                return this.tXNNumberField;
            }
            set {
                this.tXNNumberField = value;
                this.RaisePropertyChanged("TXNNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
                this.RaisePropertyChanged("TokenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tChangePasswordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string tokenNumberField;
        
        private string oldPasswordField;
        
        private string newPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
                this.RaisePropertyChanged("TokenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OldPassword {
            get {
                return this.oldPasswordField;
            }
            set {
                this.oldPasswordField = value;
                this.RaisePropertyChanged("OldPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tServiceAttrDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attrCodeField;
        
        private string attrValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AttrCode {
            get {
                return this.attrCodeField;
            }
            set {
                this.attrCodeField = value;
                this.RaisePropertyChanged("AttrCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string AttrValue {
            get {
                return this.attrValueField;
            }
            set {
                this.attrValueField = value;
                this.RaisePropertyChanged("AttrValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tServiceAttrDtoList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tServiceAttrDto serviceAttrDtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public tServiceAttrDto ServiceAttrDto {
            get {
                return this.serviceAttrDtoField;
            }
            set {
                this.serviceAttrDtoField = value;
                this.RaisePropertyChanged("ServiceAttrDto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tSetServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceNumberField;
        
        private string serviceCodeField;
        
        private string actionTypeField;
        
        private tServiceAttrDtoList serviceAttrDtoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
                this.RaisePropertyChanged("ServiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ActionType {
            get {
                return this.actionTypeField;
            }
            set {
                this.actionTypeField = value;
                this.RaisePropertyChanged("ActionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public tServiceAttrDtoList ServiceAttrDtoList {
            get {
                return this.serviceAttrDtoListField;
            }
            set {
                this.serviceAttrDtoListField = value;
                this.RaisePropertyChanged("ServiceAttrDtoList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tBillPaymentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tXNNumberField;
        
        private string userIDField;
        
        private string tokenNumberField;
        
        private string branchCodeField;
        
        private string bankCodeField;
        
        private string billNoField;
        
        private long paidAmountField;
        
        private string billStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TXNNumber {
            get {
                return this.tXNNumberField;
            }
            set {
                this.tXNNumberField = value;
                this.RaisePropertyChanged("TXNNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
                this.RaisePropertyChanged("TokenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BillNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
                this.RaisePropertyChanged("BillNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string BillStatus {
            get {
                return this.billStatusField;
            }
            set {
                this.billStatusField = value;
                this.RaisePropertyChanged("BillStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tTokenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tBillByCustRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tXNNumberField;
        
        private string userIDField;
        
        private string tokenNumberField;
        
        private string custCodeField;
        
        private string billYearMonthField;
        
        private string payStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TXNNumber {
            get {
                return this.tXNNumberField;
            }
            set {
                this.tXNNumberField = value;
                this.RaisePropertyChanged("TXNNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
                this.RaisePropertyChanged("TokenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CustCode {
            get {
                return this.custCodeField;
            }
            set {
                this.custCodeField = value;
                this.RaisePropertyChanged("CustCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BillYearMonth {
            get {
                return this.billYearMonthField;
            }
            set {
                this.billYearMonthField = value;
                this.RaisePropertyChanged("BillYearMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string PayStatus {
            get {
                return this.payStatusField;
            }
            set {
                this.payStatusField = value;
                this.RaisePropertyChanged("PayStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tBillDetailDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rowNumberField;
        
        private string billNoField;
        
        private string billMonthField;
        
        private string billYearField;
        
        private long bTCLAmountField;
        
        private long overdueAmountField;
        
        private long vATField;
        
        private string billPayStatusField;
        
        private string nameField;
        
        private string serviceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
                this.RaisePropertyChanged("RowNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string BillNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
                this.RaisePropertyChanged("BillNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string BillMonth {
            get {
                return this.billMonthField;
            }
            set {
                this.billMonthField = value;
                this.RaisePropertyChanged("BillMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string BillYear {
            get {
                return this.billYearField;
            }
            set {
                this.billYearField = value;
                this.RaisePropertyChanged("BillYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long BTCLAmount {
            get {
                return this.bTCLAmountField;
            }
            set {
                this.bTCLAmountField = value;
                this.RaisePropertyChanged("BTCLAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long OverdueAmount {
            get {
                return this.overdueAmountField;
            }
            set {
                this.overdueAmountField = value;
                this.RaisePropertyChanged("OverdueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
                this.RaisePropertyChanged("VAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string BillPayStatus {
            get {
                return this.billPayStatusField;
            }
            set {
                this.billPayStatusField = value;
                this.RaisePropertyChanged("BillPayStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
                this.RaisePropertyChanged("ServiceNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tBillDetailDtoList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tBillDetailDto billDetailDtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public tBillDetailDto BillDetailDto {
            get {
                return this.billDetailDtoField;
            }
            set {
                this.billDetailDtoField = value;
                this.RaisePropertyChanged("BillDetailDto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tBillRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tXNNumberField;
        
        private string userIDField;
        
        private string tokenNumberField;
        
        private string phoneNumberField;
        
        private string exchangeCodeField;
        
        private string accountNoField;
        
        private string billNoField;
        
        private string payStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TXNNumber {
            get {
                return this.tXNNumberField;
            }
            set {
                this.tXNNumberField = value;
                this.RaisePropertyChanged("TXNNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
                this.RaisePropertyChanged("TokenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ExchangeCode {
            get {
                return this.exchangeCodeField;
            }
            set {
                this.exchangeCodeField = value;
                this.RaisePropertyChanged("ExchangeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("AccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string BillNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
                this.RaisePropertyChanged("BillNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string PayStatus {
            get {
                return this.payStatusField;
            }
            set {
                this.payStatusField = value;
                this.RaisePropertyChanged("PayStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
    public partial class tQueryServiceStatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceNumberField;
        
        private string serviceCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
                this.RaisePropertyChanged("ServiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryServiceStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryServiceStatusRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tQueryServiceStatusRequest QueryServiceStatusRequest1;
        
        public QueryServiceStatusRequest() {
        }
        
        public QueryServiceStatusRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tQueryServiceStatusRequest QueryServiceStatusRequest1) {
            this.AuthHeader = AuthHeader;
            this.QueryServiceStatusRequest1 = QueryServiceStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryServiceStatusResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class QueryServiceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ServiceStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message;
        
        public QueryServiceStatusResponse() {
        }
        
        public QueryServiceStatusResponse(string ServiceStatus, long ResponseCode, string Message) {
            this.ServiceStatus = ServiceStatus;
            this.ResponseCode = ResponseCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tBillRequest BillRequest1;
        
        public BillRequest() {
        }
        
        public BillRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tBillRequest BillRequest1) {
            this.AuthHeader = AuthHeader;
            this.BillRequest1 = BillRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class BillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXNNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PhoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BillNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string AccountNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Message;
        
        public BillResponse() {
        }
        
        public BillResponse(string TXNNumber, string PhoneNumber, string BillNo, string AccountNo, BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList, string ResponseCode, string Message) {
            this.TXNNumber = TXNNumber;
            this.PhoneNumber = PhoneNumber;
            this.BillNo = BillNo;
            this.AccountNo = AccountNo;
            this.BillDetailDtoList = BillDetailDtoList;
            this.ResponseCode = ResponseCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillByCustRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillByCustRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tBillByCustRequest BillByCustRequest1;
        
        public BillByCustRequest() {
        }
        
        public BillByCustRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tBillByCustRequest BillByCustRequest1) {
            this.AuthHeader = AuthHeader;
            this.BillByCustRequest1 = BillByCustRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillByCustResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class BillByCustResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXNNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CustCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Message;
        
        public BillByCustResponse() {
        }
        
        public BillByCustResponse(string TXNNumber, string CustCode, BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList, string ResponseCode, string Message) {
            this.TXNNumber = TXNNumber;
            this.CustCode = CustCode;
            this.BillDetailDtoList = BillDetailDtoList;
            this.ResponseCode = ResponseCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TokenRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tTokenRequest TokenRequest1;
        
        public TokenRequest() {
        }
        
        public TokenRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tTokenRequest TokenRequest1) {
            this.AuthHeader = AuthHeader;
            this.TokenRequest1 = TokenRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TokenResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class TokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TokenNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message;
        
        public TokenResponse() {
        }
        
        public TokenResponse(string TokenNumber, long ResponseCode, string Message) {
            this.TokenNumber = TokenNumber;
            this.ResponseCode = ResponseCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillPaymentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillPaymentRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tBillPaymentRequest BillPaymentRequest1;
        
        public BillPaymentRequest() {
        }
        
        public BillPaymentRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tBillPaymentRequest BillPaymentRequest1) {
            this.AuthHeader = AuthHeader;
            this.BillPaymentRequest1 = BillPaymentRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillPaymentResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class BillPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXNNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Message;
        
        public BillPaymentResponse() {
        }
        
        public BillPaymentResponse(string ResponseCode, string TXNNumber, string Message) {
            this.ResponseCode = ResponseCode;
            this.TXNNumber = TXNNumber;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetServiceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetServiceRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tSetServiceRequest SetServiceRequest1;
        
        public SetServiceRequest() {
        }
        
        public SetServiceRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tSetServiceRequest SetServiceRequest1) {
            this.AuthHeader = AuthHeader;
            this.SetServiceRequest1 = SetServiceRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetServiceResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class SetServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message;
        
        public SetServiceResponse() {
        }
        
        public SetServiceResponse(long ResponseCode, string Message) {
            this.ResponseCode = ResponseCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tChangePasswordRequest ChangePasswordRequest1;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tChangePasswordRequest ChangePasswordRequest1) {
            this.AuthHeader = AuthHeader;
            this.ChangePasswordRequest1 = ChangePasswordRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(long ResponseCode, string Message) {
            this.ResponseCode = ResponseCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentHistoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentHistoryRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tPaymentHistoryRequest PaymentHistoryRequest1;
        
        public PaymentHistoryRequest() {
        }
        
        public PaymentHistoryRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tPaymentHistoryRequest PaymentHistoryRequest1) {
            this.AuthHeader = AuthHeader;
            this.PaymentHistoryRequest1 = PaymentHistoryRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentHistoryResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class PaymentHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList;
        
        public PaymentHistoryResponse() {
        }
        
        public PaymentHistoryResponse(string ResponseCode, string Message, BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList) {
            this.ResponseCode = ResponseCode;
            this.Message = Message;
            this.BillDetailDtoList = BillDetailDtoList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserProfile4BasicRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserProfile4BasicRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tQueryUserProfile4BasicRequest QueryUserProfile4BasicRequest1;
        
        public QueryUserProfile4BasicRequest() {
        }
        
        public QueryUserProfile4BasicRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tQueryUserProfile4BasicRequest QueryUserProfile4BasicRequest1) {
            this.AuthHeader = AuthHeader;
            this.QueryUserProfile4BasicRequest1 = QueryUserProfile4BasicRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryUserProfile4BasicResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class QueryUserProfile4BasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSISDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompletedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long CertType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CertNbr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CustType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CustName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DefLang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubsPlanCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubsPlanName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateSet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CreditLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubsID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Bal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BillingNumber;
        
        public QueryUserProfile4BasicResponse() {
        }
        
        public QueryUserProfile4BasicResponse(
                    string MSISDN, 
                    string CompletedDate, 
                    long CertType, 
                    string CertNbr, 
                    string CustType, 
                    string CustName, 
                    string Address, 
                    string DefLang, 
                    string SubsPlanCode, 
                    string SubsPlanName, 
                    string State, 
                    string StateSet, 
                    string CreditLimit, 
                    string SubsID, 
                    long Bal, 
                    string BillingNumber) {
            this.MSISDN = MSISDN;
            this.CompletedDate = CompletedDate;
            this.CertType = CertType;
            this.CertNbr = CertNbr;
            this.CustType = CustType;
            this.CustName = CustName;
            this.Address = Address;
            this.DefLang = DefLang;
            this.SubsPlanCode = SubsPlanCode;
            this.SubsPlanName = SubsPlanName;
            this.State = State;
            this.StateSet = StateSet;
            this.CreditLimit = CreditLimit;
            this.SubsID = SubsID;
            this.Bal = Bal;
            this.BillingNumber = BillingNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentCancelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://com.ztesoft.zsmart/xsd")]
        public BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentCancelRequest", Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        public BKBTitas.SvcRef_BTCLBoss.tPaymentCancelRequest PaymentCancelRequest1;
        
        public PaymentCancelRequest() {
        }
        
        public PaymentCancelRequest(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tPaymentCancelRequest PaymentCancelRequest1) {
            this.AuthHeader = AuthHeader;
            this.PaymentCancelRequest1 = PaymentCancelRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentCancelResponse", WrapperNamespace="http://com.ztesoft.zsmart/xsd", IsWrapped=true)]
    public partial class PaymentCancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXNNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.ztesoft.zsmart/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Message;
        
        public PaymentCancelResponse() {
        }
        
        public PaymentCancelResponse(string ResponseCode, string TXNNumber, string Message) {
            this.ResponseCode = ResponseCode;
            this.TXNNumber = TXNNumber;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CrmWebServicesPortTypeChannel : BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrmWebServicesPortTypeClient : System.ServiceModel.ClientBase<BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType>, BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType {
        
        public CrmWebServicesPortTypeClient() {
        }
        
        public CrmWebServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrmWebServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmWebServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmWebServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.QueryServiceStatus(BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusRequest request) {
            return base.Channel.QueryServiceStatus(request);
        }
        
        public string QueryServiceStatus(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tQueryServiceStatusRequest QueryServiceStatusRequest1, out long ResponseCode, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusRequest inValue = new BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.QueryServiceStatusRequest1 = QueryServiceStatusRequest1;
            BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).QueryServiceStatus(inValue);
            ResponseCode = retVal.ResponseCode;
            Message = retVal.Message;
            return retVal.ServiceStatus;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusResponse> QueryServiceStatusAsync(BKBTitas.SvcRef_BTCLBoss.QueryServiceStatusRequest request) {
            return base.Channel.QueryServiceStatusAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.BillResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.Bill(BKBTitas.SvcRef_BTCLBoss.BillRequest request) {
            return base.Channel.Bill(request);
        }
        
        public string Bill(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tBillRequest BillRequest1, out string PhoneNumber, out string BillNo, out string AccountNo, out BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList, out string ResponseCode, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.BillRequest inValue = new BKBTitas.SvcRef_BTCLBoss.BillRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.BillRequest1 = BillRequest1;
            BKBTitas.SvcRef_BTCLBoss.BillResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).Bill(inValue);
            PhoneNumber = retVal.PhoneNumber;
            BillNo = retVal.BillNo;
            AccountNo = retVal.AccountNo;
            BillDetailDtoList = retVal.BillDetailDtoList;
            ResponseCode = retVal.ResponseCode;
            Message = retVal.Message;
            return retVal.TXNNumber;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.BillResponse> BillAsync(BKBTitas.SvcRef_BTCLBoss.BillRequest request) {
            return base.Channel.BillAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.BillByCustResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.BillByCust(BKBTitas.SvcRef_BTCLBoss.BillByCustRequest request) {
            return base.Channel.BillByCust(request);
        }
        
        public string BillByCust(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tBillByCustRequest BillByCustRequest1, out string CustCode, out BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList, out string ResponseCode, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.BillByCustRequest inValue = new BKBTitas.SvcRef_BTCLBoss.BillByCustRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.BillByCustRequest1 = BillByCustRequest1;
            BKBTitas.SvcRef_BTCLBoss.BillByCustResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).BillByCust(inValue);
            CustCode = retVal.CustCode;
            BillDetailDtoList = retVal.BillDetailDtoList;
            ResponseCode = retVal.ResponseCode;
            Message = retVal.Message;
            return retVal.TXNNumber;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.BillByCustResponse> BillByCustAsync(BKBTitas.SvcRef_BTCLBoss.BillByCustRequest request) {
            return base.Channel.BillByCustAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.TokenResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.Token(BKBTitas.SvcRef_BTCLBoss.TokenRequest request) {
            return base.Channel.Token(request);
        }
        
        public string Token(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tTokenRequest TokenRequest1, out long ResponseCode, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.TokenRequest inValue = new BKBTitas.SvcRef_BTCLBoss.TokenRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.TokenRequest1 = TokenRequest1;
            BKBTitas.SvcRef_BTCLBoss.TokenResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).Token(inValue);
            ResponseCode = retVal.ResponseCode;
            Message = retVal.Message;
            return retVal.TokenNumber;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.TokenResponse> TokenAsync(BKBTitas.SvcRef_BTCLBoss.TokenRequest request) {
            return base.Channel.TokenAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.BillPaymentResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.BillPayment(BKBTitas.SvcRef_BTCLBoss.BillPaymentRequest request) {
            return base.Channel.BillPayment(request);
        }
        
        public string BillPayment(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tBillPaymentRequest BillPaymentRequest1, out string TXNNumber, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.BillPaymentRequest inValue = new BKBTitas.SvcRef_BTCLBoss.BillPaymentRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.BillPaymentRequest1 = BillPaymentRequest1;
            BKBTitas.SvcRef_BTCLBoss.BillPaymentResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).BillPayment(inValue);
            TXNNumber = retVal.TXNNumber;
            Message = retVal.Message;
            return retVal.ResponseCode;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.BillPaymentResponse> BillPaymentAsync(BKBTitas.SvcRef_BTCLBoss.BillPaymentRequest request) {
            return base.Channel.BillPaymentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.SetServiceResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.SetService(BKBTitas.SvcRef_BTCLBoss.SetServiceRequest request) {
            return base.Channel.SetService(request);
        }
        
        public long SetService(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tSetServiceRequest SetServiceRequest1, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.SetServiceRequest inValue = new BKBTitas.SvcRef_BTCLBoss.SetServiceRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.SetServiceRequest1 = SetServiceRequest1;
            BKBTitas.SvcRef_BTCLBoss.SetServiceResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).SetService(inValue);
            Message = retVal.Message;
            return retVal.ResponseCode;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.SetServiceResponse> SetServiceAsync(BKBTitas.SvcRef_BTCLBoss.SetServiceRequest request) {
            return base.Channel.SetServiceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.ChangePasswordResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.ChangePassword(BKBTitas.SvcRef_BTCLBoss.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public long ChangePassword(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tChangePasswordRequest ChangePasswordRequest1, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.ChangePasswordRequest inValue = new BKBTitas.SvcRef_BTCLBoss.ChangePasswordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ChangePasswordRequest1 = ChangePasswordRequest1;
            BKBTitas.SvcRef_BTCLBoss.ChangePasswordResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).ChangePassword(inValue);
            Message = retVal.Message;
            return retVal.ResponseCode;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.ChangePasswordResponse> ChangePasswordAsync(BKBTitas.SvcRef_BTCLBoss.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.PaymentHistoryResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.PaymentHistory(BKBTitas.SvcRef_BTCLBoss.PaymentHistoryRequest request) {
            return base.Channel.PaymentHistory(request);
        }
        
        public string PaymentHistory(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tPaymentHistoryRequest PaymentHistoryRequest1, out string Message, out BKBTitas.SvcRef_BTCLBoss.tBillDetailDtoList BillDetailDtoList) {
            BKBTitas.SvcRef_BTCLBoss.PaymentHistoryRequest inValue = new BKBTitas.SvcRef_BTCLBoss.PaymentHistoryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.PaymentHistoryRequest1 = PaymentHistoryRequest1;
            BKBTitas.SvcRef_BTCLBoss.PaymentHistoryResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).PaymentHistory(inValue);
            Message = retVal.Message;
            BillDetailDtoList = retVal.BillDetailDtoList;
            return retVal.ResponseCode;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.PaymentHistoryResponse> PaymentHistoryAsync(BKBTitas.SvcRef_BTCLBoss.PaymentHistoryRequest request) {
            return base.Channel.PaymentHistoryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.QueryUserProfile4Basic(BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicRequest request) {
            return base.Channel.QueryUserProfile4Basic(request);
        }
        
        public string QueryUserProfile4Basic(
                    BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, 
                    BKBTitas.SvcRef_BTCLBoss.tQueryUserProfile4BasicRequest QueryUserProfile4BasicRequest1, 
                    out string CompletedDate, 
                    out long CertType, 
                    out string CertNbr, 
                    out string CustType, 
                    out string CustName, 
                    out string Address, 
                    out string DefLang, 
                    out string SubsPlanCode, 
                    out string SubsPlanName, 
                    out string State, 
                    out string StateSet, 
                    out string CreditLimit, 
                    out string SubsID, 
                    out long Bal, 
                    out string BillingNumber) {
            BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicRequest inValue = new BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.QueryUserProfile4BasicRequest1 = QueryUserProfile4BasicRequest1;
            BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).QueryUserProfile4Basic(inValue);
            CompletedDate = retVal.CompletedDate;
            CertType = retVal.CertType;
            CertNbr = retVal.CertNbr;
            CustType = retVal.CustType;
            CustName = retVal.CustName;
            Address = retVal.Address;
            DefLang = retVal.DefLang;
            SubsPlanCode = retVal.SubsPlanCode;
            SubsPlanName = retVal.SubsPlanName;
            State = retVal.State;
            StateSet = retVal.StateSet;
            CreditLimit = retVal.CreditLimit;
            SubsID = retVal.SubsID;
            Bal = retVal.Bal;
            BillingNumber = retVal.BillingNumber;
            return retVal.MSISDN;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicResponse> QueryUserProfile4BasicAsync(BKBTitas.SvcRef_BTCLBoss.QueryUserProfile4BasicRequest request) {
            return base.Channel.QueryUserProfile4BasicAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BKBTitas.SvcRef_BTCLBoss.PaymentCancelResponse BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType.PaymentCancel(BKBTitas.SvcRef_BTCLBoss.PaymentCancelRequest request) {
            return base.Channel.PaymentCancel(request);
        }
        
        public string PaymentCancel(BKBTitas.SvcRef_BTCLBoss.tAuthHeader AuthHeader, BKBTitas.SvcRef_BTCLBoss.tPaymentCancelRequest PaymentCancelRequest1, out string TXNNumber, out string Message) {
            BKBTitas.SvcRef_BTCLBoss.PaymentCancelRequest inValue = new BKBTitas.SvcRef_BTCLBoss.PaymentCancelRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.PaymentCancelRequest1 = PaymentCancelRequest1;
            BKBTitas.SvcRef_BTCLBoss.PaymentCancelResponse retVal = ((BKBTitas.SvcRef_BTCLBoss.CrmWebServicesPortType)(this)).PaymentCancel(inValue);
            TXNNumber = retVal.TXNNumber;
            Message = retVal.Message;
            return retVal.ResponseCode;
        }
        
        public System.Threading.Tasks.Task<BKBTitas.SvcRef_BTCLBoss.PaymentCancelResponse> PaymentCancelAsync(BKBTitas.SvcRef_BTCLBoss.PaymentCancelRequest request) {
            return base.Channel.PaymentCancelAsync(request);
        }
    }
}
