//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BKBTitasEntities : DbContext
    {
        public BKBTitasEntities()
            : base("name=BKBTitasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BtclBillDetail> BtclBillDetails { get; set; }
        public virtual DbSet<BtclBillDetailLog> BtclBillDetailLogs { get; set; }
        public virtual DbSet<BTCLTxnID> BTCLTxnIDs { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<MainMenu> MainMenus { get; set; }
        public virtual DbSet<MeteredBillDetail> MeteredBillDetails { get; set; }
        public virtual DbSet<NonMeterBillDetail> NonMeterBillDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleMenuMapping> RoleMenuMappings { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<TitasZone> TitasZones { get; set; }
        public virtual DbSet<BankTxnIDSequence> BankTxnIDSequences { get; set; }
        public virtual DbSet<BTCLDailyReport> BTCLDailyReports { get; set; }
        public virtual DbSet<BTCLMonthlyReport> BTCLMonthlyReports { get; set; }
        public virtual DbSet<MeteredReport> MeteredReports { get; set; }
        public virtual DbSet<Non_MeteredReport> Non_MeteredReport { get; set; }
    
        public virtual ObjectResult<BranchWiseBTCLBillDetails_Result> BranchWiseBTCLBillDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseBTCLBillDetails_Result>("BranchWiseBTCLBillDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseMeterCancelDetails_Result> BranchWiseMeterCancelDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseMeterCancelDetails_Result>("BranchWiseMeterCancelDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseMeterCustDetails_Result> BranchWiseMeterCustDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseMeterCustDetails_Result>("BranchWiseMeterCustDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseMeterDetails_Result> BranchWiseMeterDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseMeterDetails_Result>("BranchWiseMeterDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseMeterSummary_Result> BranchWiseMeterSummary(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseMeterSummary_Result>("BranchWiseMeterSummary", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNMDNoteCancelDetails_Result> BranchWiseNMDNoteCancelDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNMDNoteCancelDetails_Result>("BranchWiseNMDNoteCancelDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNMDNoteDetails_Result> BranchWiseNMDNoteDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNMDNoteDetails_Result>("BranchWiseNMDNoteDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNonMeterCancelDetails_Result> BranchWiseNonMeterCancelDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNonMeterCancelDetails_Result>("BranchWiseNonMeterCancelDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNonMeterCustDetails_Result> BranchWiseNonMeterCustDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNonMeterCustDetails_Result>("BranchWiseNonMeterCustDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNonMeterDetails_Result> BranchWiseNonMeterDetails(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNonMeterDetails_Result>("BranchWiseNonMeterDetails", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNonMeterDNoteSummary_Result> BranchWiseNonMeterDNoteSummary(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNonMeterDNoteSummary_Result>("BranchWiseNonMeterDNoteSummary", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNonMeterDNSummary_Result> BranchWiseNonMeterDNSummary(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNonMeterDNSummary_Result>("BranchWiseNonMeterDNSummary", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchWiseNonMeterSummary_Result> BranchWiseNonMeterSummary(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchWiseNonMeterSummary_Result>("BranchWiseNonMeterSummary", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<BranchZoneNonMeterSummary_Result> BranchZoneNonMeterSummary(string dtFrom, string dtTo, string branch)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchZoneNonMeterSummary_Result>("BranchZoneNonMeterSummary", dtFromParameter, dtToParameter, branchParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> GetBankTxnID(ObjectParameter value)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetBankTxnID", value);
        }
    
        public virtual ObjectResult<Nullable<long>> GetBtclBankTxnID(ObjectParameter value)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetBtclBankTxnID", value);
        }
    
        public virtual int GetBTCLTxnSEQUENCE(ObjectParameter value)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetBTCLTxnSEQUENCE", value);
        }
    
        public virtual int GetSEQUENCE(ObjectParameter value)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSEQUENCE", value);
        }
    
        public virtual ObjectResult<ZoneWiseSummary_Result> ZoneWiseSummary(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZoneWiseSummary_Result>("ZoneWiseSummary", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<ZoneWiseSummaryDNNon_Result> ZoneWiseSummaryDNNon(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZoneWiseSummaryDNNon_Result>("ZoneWiseSummaryDNNon", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    
        public virtual ObjectResult<ZoneWiseSummaryNon_Result> ZoneWiseSummaryNon(string dtFrom, string dtTo, string branch, string userRole)
        {
            var dtFromParameter = dtFrom != null ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(string));
    
            var dtToParameter = dtTo != null ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZoneWiseSummaryNon_Result>("ZoneWiseSummaryNon", dtFromParameter, dtToParameter, branchParameter, userRoleParameter);
        }
    }
}
