//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTCLMonthlyReport
    {
        public string Bill_No___Invoice_ID { get; set; }
        public string PhoneNumber { get; set; }
        public string BillMonth { get; set; }
        public string BillYear { get; set; }
        public decimal Bill_amount { get; set; }
        public decimal VAT { get; set; }
        public decimal TotalAmount { get; set; }
        public string TxnNumber { get; set; }
    }
}
