//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BtclBillDetailLog
    {
        public int LogId { get; set; }
        public string BranchCode { get; set; }
        public string BtclBranchCode { get; set; }
        public string BillNumber { get; set; }
        public string ExchangeCode { get; set; }
        public string PhoneNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Name { get; set; }
        public string LastPayDate { get; set; }
        public string TxnNumber { get; set; }
        public string BillMonth { get; set; }
        public string BillYear { get; set; }
        public decimal BTCLAmount { get; set; }
        public decimal OverdueAmount { get; set; }
        public decimal VAT { get; set; }
        public decimal TotalAmount { get; set; }
        public string BillPayStatus { get; set; }
        public string ServiceNumber { get; set; }
        public string NewPayStatus { get; set; }
        public string CancelReason { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<System.DateTime> Canceledon { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Createon { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string Ureatedby { get; set; }
    }
}
