//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeteredBillDetail
    {
        public int id { get; set; }
        public int paymentId { get; set; }
        public string transactionDate { get; set; }
        public string customerCode { get; set; }
        public string transactionStatus { get; set; }
        public string invoiceNo { get; set; }
        public decimal invoiceAmount { get; set; }
        public decimal paidAmount { get; set; }
        public decimal sourceTaxAmount { get; set; }
        public decimal revenueStamp { get; set; }
        public string zone { get; set; }
        public string creator { get; set; }
        public string creationTime { get; set; }
        public string postingTime { get; set; }
        public string bankCode { get; set; }
        public string branchCode { get; set; }
        public string branchRoutingNo { get; set; }
        public string @operator { get; set; }
        public string refNo { get; set; }
        public string reason { get; set; }
        public string cancelOperator { get; set; }
        public string chalanNo { get; set; }
        public string chalanDate { get; set; }
        public string chalanBank { get; set; }
        public string chalanBranch { get; set; }
        public string remarks { get; set; }
        public string updateFlag { get; set; }
        public string updateOperator { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerName { get; set; }
        public string custAddress { get; set; }
        public string issueMonth { get; set; }
        public string issueDate { get; set; }
        public Nullable<System.DateTime> transactionDateTime { get; set; }
        public string settaleDate { get; set; }
    }
}
