//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBTitas.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitasZone
    {
        public int id { get; set; }
        public string zoneName { get; set; }
        public string zoneCode { get; set; }
        public string zoneMobile { get; set; }
        public string zoneEmail { get; set; }
        public string isDuplicate { get; set; }
    }
}
